AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template EC2InstanceWithSecurityGroupSample: Create
  an Amazon EC2 instance running the Amazon Linux AMI. The AMI is chosen based
  on the region in which the stack is run. This example creates an EC2 security
  group for the instance to give you SSH access. **WARNING** This template
  creates an Amazon EC2 instance. You will be billed for the AWS resources used
  if you create a stack from this template.
Parameters:
  KeyName:
    Default: Primary Keys
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    AllowedValues:
      - Primary Keys
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
    Metadata:
      'AWS::CloudFormation::Designer':
        id: dd3ae3a6-2caf-4b35-9b96-b77b81e8f16b
  nodemaster:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyName
      ImageId: ami-0ac05733838eabc06
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              apt-get update -y && sudo apt-get upgrade -y
              # Install Java 8
              apt-get install openjdk-8-jdk -y
              useradd -u 12345 -g users -m -s /bin/bash -p hadoop hadoop
              su - hadoop
              cd /home/hadoop/
              wget http://apache.cs.utah.edu/hadoop/common/current/hadoop-3.1.2.tar.gz
              tar -xzf hadoop-3.1.2.tar.gz
              mv hadoop-3.1.2 hadoop
            - |
              # Install the files and packages from the metadata
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource WebServerInstance '
            - '         --configsets Install '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0a226bb8-e762-4d35-b7ad-87d08e1b4af9
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref nodemaster
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 
      - nodemaster
      - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt 
      - nodemaster
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 
      - nodemaster
      - PublicIp
Metadata:
  'AWS::CloudFormation::Designer':
    dd3ae3a6-2caf-4b35-9b96-b77b81e8f16b:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    0a226bb8-e762-4d35-b7ad-87d08e1b4af9:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - dd3ae3a6-2caf-4b35-9b96-b77b81e8f16b
    4a226bb8-e762-4d35-b7ad-87d08e1b4af9:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 30
      z: 1
      embeds: []
      isassociatedwith:
        - dd3ae3a6-2caf-4b35-9b96-b77b81e8f16b
    12226bb8-e762-4d35-b7ad-87d08e1b4af9:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 150
      z: 1
      embeds: []
      isassociatedwith:
        - dd3ae3a6-2caf-4b35-9b96-b77b81e8f16b
